<?php
/**
 * @file
 * Provides the ability for a link tags with target="_blank" to be 
 * automatically converted to a more accessible format, by alerting users via 
 * the use of text that the link will open in a new window.
 *
 * The text to be displayed can be changed via the filter settings form
 */

function accessibletargetblankfilter_init() {
    
    drupal_add_css(drupal_get_path('module', 'accessibletargetblankfilter') . '/accessibletargetblankfilter.css');
    drupal_add_js(drupal_get_path('module', 'accessibletargetblankfilter') . '/accessibletargetblankfilter.js', 'file');
    
}

/*
 * sets the default text that the filter will insert
 * 
 */

function _accessibletargetblank_getDefaultText() {
    return 'This link will open in a new window';
}

/**
 * Implements hook_filter_info().
 */
function accessibletargetblankfilter_filter_info() {
  
  $filters['accessibletargetblankfilter'] = array(
    'title' => t('Accessible Target Blank Filter'),
    'description' => t('Converts links that open in a new window and that have no title attribute to a more accessible format'),
    'process callback' => '_accessibletargetblankfilter_process',
    'default settings' => array(
      'accessibletargetblankfilter_texttoadd' => _accessibletargetblank_getDefaultText(),
    ),
    'settings callback' => '_accessibletargetblankfilter_settings',
    'tips callback' => 'accessibletargetblankfilter_filter_tips',
  );
  return $filters;
}

/**
 * Implements hook_filter_tips().
 */
function accessibletargetblankfilter_filter_tips($filter, $format, $long = FALSE) {
  
  $textToAdd = isset($filter->settings['accessibletargetblankfilter_texttoadd']) ? $filter->settings['accessibletargetblankfilter_texttoadd'] : accessibletargetblank_getDefaultText();
  
  if ($long) {
    return t('Text to be added to the link tag to denote that it will open in a new window. The current text is ' . $textToAdd);
  }
  else {
    return t('Text to be added to the link tag to denote that it will open in a new window. The current text is ' . $textToAdd);
  }
}

/**
 * Process function for the highlight filter.
 */
function _accessibletargetblankfilter_process($text, $filter) {
  
  $textToAdd = isset($filter->settings['accessibletargetblankfilter_texttoadd']) ? $filter->settings['accessibletargetblankfilter_texttoadd'] : accessibletargetblank_getDefaultText();
  $pattern = '~<a\s++[^>]*?\btarget\s*+=\s*+([\'"])_blank\1[^>]*+>\K((?:[^<]++|<++(?!/a>))*+)~is';
  
  return preg_replace($pattern, "$2<span class=\"linkTargetBlankChild\">" . $textToAdd . "</span>", $text);
  
}

/**
 * The settings form for filter.
 *
 * Default text is set above in the function... something like "This link will open in a new window"
 */
function _accessibletargetblankfilter_settings($form, &$form_state, $filter, $format, $defaults) {
  $filter->settings += $defaults;

  $settings['accessibletargetblankfilter_texttoadd'] = array(
    '#title' => t('Text to add'),
    '#description' => t('Text to be added to the link tag to denote that it will open in a new window'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => isset($filter->settings['accessibletargetblankfilter_texttoadd']) ? $filter->settings['accessibletargetblankfilter_texttoadd'] : $defaults['accessibletargetblankfilter_texttoadd'],
  );
  
  return $settings;
}